	<article>
	<div class="menu">
	<ul>
		<li><a href="form_religiao.php">Cadastrar Religião</a></li>
		<li><a href="form_pais.php">Cadastrar País</a></li>
		<li><a href="religiao_pais.php">Relação de Religião e País</a></li>
		<li><a href="listagem_religiao.php">Lista de Religiões</a></li>
		<li><a href="listagem_pais.php">Lista de Países</a></li>
		<li><a href="listagem_religiao_pais.php">Lista de Religiões e Países</a></li>
	</ul>
	</div>
</article>